apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapid-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rapid-app
  template:
    metadata:
      labels:
        app: rapid-app
    spec:
      containers:
      - name: rapid-container
        image: ashraful90/rapidcompetitions:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: rapid-secret
              key: SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: rapid-service
spec:
  type: NodePort
  selector:
    app: rapid-app
  ports:
  - port: 8000
    targetPort: 8000
